objects/ApexElements__c.object
<CustomObject>
    <fields>
        <fullName>ApexElement__c</fullName>
        <externalId>true</externalId>
        <label>Apex Element</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Apex Elements</relationshipLabel>
        <relationshipName>Apex_Elements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Apex Element</label>
    <nameField>
        <label>Apex Element</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deployment__c.object
<CustomObject>
    <fields>
        <fullName>NoTestWarning__c</fullName>
        <label>No Test Warning</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Package__c</fullName>
        <label>Package</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RunTest__c</fullName>
        <label>Run Test</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ManualTask__c.object
<CustomObject>
    <fields>
        <fullName>Deployment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Manual Tasks</relationshipLabel>
        <relationshipName>Manual_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Manual Tasks</relationshipLabel>
        <relationshipName>ManualTasks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Manual Task</label>
    <nameField>
        <displayFormat>MT{00000000}</displayFormat>
        <label>Manual Task</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Projects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Deployment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>NoTestWarning__c</fullName>
        <label>No Test Warning</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Package__c</fullName>
        <label>Package</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RunTest__c</fullName>
        <label>Run Tests</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TaskItem__c.object
<CustomObject>
    <fields>
        <fullName>TaskItemType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Task Item Type</label>
        <referenceTo>TaskItemType__c</referenceTo>
        <relationshipLabel>Task Items</relationshipLabel>
        <relationshipName>Task_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaskItem__c</fullName>
        <inlineHelpText>Campos,Workflows: NombreAPIdelObjeto.NombreDelCampo
Layouts: NombreAPIdelObjeto-Nombre Del Layout
EmailTemp,Dashb.,Documents, Reports unfiled$public/NombreDeLaTemp (o) carpeta/NombreDeLaTemp</inlineHelpText>
        <label>Task Item</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Task Items</relationshipLabel>
        <relationshipName>Task_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Task Item</label>
    <nameField>
        <displayFormat>TI{00000000}</displayFormat>
        <label>Task Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TaskItemType__c.object
<CustomObject>
    <fields>
        <fullName>TaskItemType__c</fullName>
        <externalId>true</externalId>
        <label>Task Item Type</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Task Item Type</label>
    <nameField>
        <label>Task Item Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Item Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TestClass__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Test Classes</relationshipLabel>
        <relationshipName>Test_Classes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TestClass__c</fullName>
        <label>Test Class</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Test Class</label>
    <nameField>
        <label>Test Class</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TestForApexElement__c.object
<CustomObject>
    <fields>
        <fullName>ApexElement__c</fullName>
        <label>Apex Element</label>
        <referenceTo>ApexElements__c</referenceTo>
        <relationshipLabel>Tests For Apex Element</relationshipLabel>
        <relationshipName>Tests_For_Apex_Element</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tests For Apex Element</relationshipLabel>
        <relationshipName>Tests_For_Apex_Element</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TestClass__c</fullName>
        <label>Test Class</label>
        <referenceTo>TestClass__c</referenceTo>
        <relationshipLabel>Tests For Apex Element</relationshipLabel>
        <relationshipName>Tests_For_Apex_Element</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test For Apex Element</label>
    <nameField>
        <displayFormat>TFAE#{0000000}</displayFormat>
        <label>TFAE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tests For Apex Element</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PackageBuilder_Test.cls
@isTest
public with sharing class PackageBuilder_Test {
    
    @TestSetup
    private static void makeData(){
        Project__c p = TestUtility.createProject('TestProject0');
        insert p;

        TaskItemType__c tit = TestUtility.createTaskItemType('ApexClass');
        insert tit;
        
        Task__c t = TestUtility.createTask('TestTask0', p.Id);
        insert t;

    }

    @isTest
    private static void testForManualTask(){
        Task__c theTask = [SELECT Id, project__c FROM Task__c LIMIT 1];
        insert new ManualTask__c(
            Description__c = 'stuff to do',
            Task__c = theTask.Id
        );

        Deployment__c dep = TestUtility.createDeployment('Aweseome Task Manager Deployment');
        insert dep;

        theTask.Deployment__c = dep.Id;
        update theTask;

        ManualTask__c theMT = [SELECT Id, Deployment__c FROM ManualTask__c LIMIT 1];
        System.assertEquals(dep.Id, theMT.Deployment__c);
    }

    @isTest
    private static void testForDeployment(){
        Deployment__c dep = TestUtility.createDeployment('Aweseome Task Manager Deployment');
        insert dep;

        Project__c p = [SELECT Id FROM Project__c LIMIT 1];

        Task__c t0 = TestUtility.createTask('TestTask0a', p.Id);
        t0.Deployment__c = dep.Id;
        insert t0;

        Task__c t1 = TestUtility.createTask('TestTask1', p.Id);
        t1.Deployment__c = dep.Id;
        insert t1;

        TaskItemType__c tit = [SELECT Id, Name FROM TaskItemType__c LIMIT 1];


        list<TaskItem__c> tiList = new list<TaskItem__c>{
            new TaskItem__c(
                TaskItem__c = 'Class0',
                Task__c = t0.Id,
                TaskItemType__c = tit.Id
            ),
            new TaskItem__c(
                TaskItem__c = 'Class1',
                Task__c = t0.Id,
                TaskItemType__c = tit.Id
            ),
            new TaskItem__c(
                TaskItem__c = 'Class2',
                Task__c = t1.Id,
                TaskItemType__c = tit.Id
            ),
            new TaskItem__c(
                TaskItem__c = 'Class3',
                Task__c = t1.Id,
                TaskItemType__c = tit.Id
            )


        };
        insert tiList;
        map<String, String> tiByTaskItem = Util.clasifySecondFieldByFirstField(tiList, 'TaskItem__c', 'Id');


        t0 = [SELECT Id, Package__c,project__c,NoTestWarning__c,RunTest__c FROM Task__c WHERE Name = 'TestTask0a'];
        t1 = [SELECT Id, Package__c,project__c,NoTestWarning__c,RunTest__c FROM Task__c WHERE Name = 'TestTask1'];

        dep = [SELECT Id, Package__c FROM Deployment__c LIMIT 1];

        System.assert(t0.Package__c.contains('Class0'), 'Package is not as expected: '+t0.Package__c);
        System.assert(t0.Package__c.contains('Class1'), 'Package is not as expected: '+t0.Package__c);
        System.assert(!t0.Package__c.contains('Class2'), 'Package is not as expected: '+t0.Package__c);
        System.assert(!t0.Package__c.contains('Class3'), 'Package is not as expected: '+t0.Package__c);

        System.assert(t1.Package__c.contains('Class2'), 'Package is not as expected: '+t1.Package__c);
        System.assert(t1.Package__c.contains('Class3'), 'Package is not as expected: '+t1.Package__c);
        System.assert(!t1.Package__c.contains('Class0'), 'Package is not as expected: '+t1.Package__c);
        System.assert(!t1.Package__c.contains('Class1'), 'Package is not as expected: '+t1.Package__c);

        System.assert(dep.Package__c.contains('Class2'), 'Package is not as expected: '+dep.Package__c);
        System.assert(dep.Package__c.contains('Class3'), 'Package is not as expected: '+dep.Package__c);
        System.assert(dep.Package__c.contains('Class0'), 'Package is not as expected: '+dep.Package__c);
        System.assert(dep.Package__c.contains('Class1'), 'Package is not as expected: '+dep.Package__c);

        t1.Deployment__c = null;
        update t1;

        dep = [SELECT Id, Package__c FROM Deployment__c LIMIT 1];
        System.assert(!dep.Package__c.contains('Class2'), 'Package is not as expected: '+dep.Package__c);
        System.assert(!dep.Package__c.contains('Class3'), 'Package is not as expected: '+dep.Package__c);
        System.assert(dep.Package__c.contains('Class0'), 'Package is not as expected: '+dep.Package__c);
        System.assert(dep.Package__c.contains('Class1'), 'Package is not as expected: '+dep.Package__c);

        delete tiList[3];

        t1 = [SELECT Id, Package__c,project__c,NoTestWarning__c,RunTest__c FROM Task__c WHERE Name = 'TestTask1'];
        System.assert(t1.Package__c.contains('Class2'), 'Package is not as expected: '+t1.Package__c);
        System.assert(!t1.Package__c.contains('Class3'), 'Package is not as expected: '+t1.Package__c);

        delete tiList[0];
        dep = [SELECT Id, Package__c FROM Deployment__c LIMIT 1];
        System.assert(!dep.Package__c.contains('Class2'), 'Package is not as expected: '+dep.Package__c);
        System.assert(!dep.Package__c.contains('Class3'), 'Package is not as expected: '+dep.Package__c);
        System.assert(!dep.Package__c.contains('Class0'), 'Package is not as expected: '+dep.Package__c);
        System.assert(dep.Package__c.contains('Class1'), 'Package is not as expected: '+dep.Package__c);
        System.assert(dep.Package__c.contains('ApexClass'), 'Package is not as expected: '+dep.Package__c);

        tit.Name = 'ApexCLASSS';
        System.debug('Update taskitemType Name');

        update tit;
        dep = [SELECT Id, Package__c FROM Deployment__c LIMIT 1];
        System.assert(!dep.Package__c.contains('ApexClass'), 'Package is not as expected: '+dep.Package__c);
        System.assert(dep.Package__c.contains('ApexCLASSS'), 'Package is not as expected: '+dep.Package__c);




    }

    @isTest
    private static void testForPackage(){


        Task__c theTask = [SELECT Id, project__c FROM Task__c LIMIT 1];
        TaskItemType__c tit = [SELECT Id FROM TaskItemType__c LIMIT 1];

        insert new TaskItem__c(
            TaskItem__c = 'PackageBuilder_Test',
            Task__c = theTask.Id,
            TaskItemType__c = tit.Id
        );
        insert new TaskItem__c(
            TaskItem__c = 'PackageBuilder',
            Task__c = theTask.Id,
            TaskItemType__c = tit.Id
        );


        theTask = [SELECT Id, Package__c,project__c,NoTestWarning__c,RunTest__c FROM Task__c LIMIT 1];

        System.assert(theTask.Package__c.contains('PackageBuilder_Test'), 'Package is not as expected: '+theTask.Package__c);
        System.assert(theTask.Package__c.contains('ApexClass'), 'Package is not as expected: '+theTask.Package__c);
        System.assert(theTask.NoTestWarning__c.contains('PackageBuilder'), 'NoTestWarning__c is not as expected: '+theTask.NoTestWarning__c);
        System.assert(theTask.RunTest__c==null, 'RunTest__c is not as expected: '+theTask.RunTest__c);

        Deployment__c dep = TestUtility.createDeployment('Aweseome Task Manager Deployment');
        insert dep;

        theTask.Deployment__c = dep.Id;
        update theTask;

        ApexElements__c ae = TestUtility.createApexElement('PackageBuilder', theTask.Project__c);
        insert ae;

        TestClass__c tc = TestUtility.createTestClass('PackageBuilder_Test', theTask.Project__c);
        insert tc;

        TestClass__c tc2 = TestUtility.createTestClass('RandomTest', theTask.Project__c);
        insert tc2;

        TestClass__c tc3 = TestUtility.createTestClass('RandomTest2', theTask.Project__c);
        insert tc3;

        TestForApexElement__c tfae0 = new TestForApexElement__c(
            ApexElement__c = ae.Id,
            TestClass__c = tc.Id
        );
        insert tfae0;

        TestForApexElement__c tfae1 = new TestForApexElement__c(
            ApexElement__c = ae.Id,
            TestClass__c = tc2.Id
        );
        insert tfae1;

        TaskItem__c newTI = new TaskItem__c(
            TaskItem__c = 'ApexElements_UTIL',
            Task__c = theTask.Id,
            TaskItemType__c = tit.Id
        );
        insert newTI;

        theTask = [SELECT Id, Package__c,project__c,RunTest__c,NoTestWarning__c FROM Task__c LIMIT 1];
        System.assert(theTask.Package__c.contains('ApexElements_UTIL'), 'Package is not as expected: '+theTask.Package__c);
        System.assert(theTask.RunTest__c.contains('<runTest>PackageBuilder_Test</runTest>'), 'RunTest__c is not as expected: '+theTask.RunTest__c);
        System.assert(theTask.RunTest__c.contains('<runTest>RandomTest</runTest>'), 'RunTest__c is not as expected: '+theTask.RunTest__c);
        System.assert(theTask.NoTestWarning__c.contains('ApexElements_UTIL'), 'NoTestWarning__c is not as expected: '+theTask.NoTestWarning__c);

        newTI.TaskItem__c = 'ApexElements_Util';
        update newTI;
        theTask = [SELECT Id, Package__c,project__c,RunTest__c,NoTestWarning__c FROM Task__c LIMIT 1];
        System.assert(theTask.Package__c.contains('ApexElements_Util'), 'Package is not as expected: '+theTask.Package__c);
        System.assert(!theTask.Package__c.contains('ApexElements_UTIL'), 'Package is not as expected: '+theTask.Package__c);
        System.assert(theTask.NoTestWarning__c.contains('ApexElements_Util'), 'NoTestWarning__c is not as expected: '+theTask.NoTestWarning__c);
        System.assert(!theTask.NoTestWarning__c.contains('ApexElements_UTIL'), 'NoTestWarning__c is not as expected: '+theTask.NoTestWarning__c);

        ApexElements__c ae1 = TestUtility.createApexElement('ApexElements_TILU', theTask.Project__c);
        insert ae1;

        TestForApexElement__c tfae2 = new TestForApexElement__c(
            ApexElement__c = ae1.Id,
            TestClass__c = tc3.Id
        );
        insert tfae2;

        theTask = [SELECT Id, Package__c,project__c,RunTest__c,NoTestWarning__c FROM Task__c LIMIT 1];
        System.assert(!theTask.RunTest__c.contains('<runTest>RandomTest2</runTest>'), 'RunTest__c is not as expected: '+theTask.RunTest__c);

        ae1.Name = 'ApexElements_Util';
        System.debug('Update apex element');

        update ae1;

        theTask = [SELECT Id, Package__c,project__c,RunTest__c,NoTestWarning__c FROM Task__c LIMIT 1];
        System.assert(theTask.RunTest__c.contains('<runTest>RandomTest2</runTest>'), 'RunTest__c is not as expected: '+theTask.RunTest__c);

        tc3.Name = 'RandomTest3';
        System.debug('Update apex test class');

        update tc3;

        theTask = [SELECT Id, Package__c,project__c,RunTest__c,NoTestWarning__c FROM Task__c LIMIT 1];
        System.assert(!theTask.RunTest__c.contains('<runTest>RandomTest2</runTest>'), 'RunTest__c is not as expected: '+theTask.RunTest__c);
        System.assert(theTask.RunTest__c.contains('<runTest>RandomTest3</runTest>'), 'RunTest__c is not as expected: '+theTask.RunTest__c);
    }
}