objects/ApexElements__c.object
<CustomObject>
    <fields>
        <fullName>ApexElement__c</fullName>
        <externalId>true</externalId>
        <label>Apex Element</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Apex Elements</relationshipLabel>
        <relationshipName>Apex_Elements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Apex Element</label>
    <nameField>
        <label>Apex Element</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Projects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/TestForApexElement__c.object
<CustomObject>
    <fields>
        <fullName>ApexElement__c</fullName>
        <label>Apex Element</label>
        <referenceTo>ApexElements__c</referenceTo>
        <relationshipLabel>Tests For Apex Element</relationshipLabel>
        <relationshipName>Tests_For_Apex_Element</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tests For Apex Element</relationshipLabel>
        <relationshipName>Tests_For_Apex_Element</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test For Apex Element</label>
    <nameField>
        <displayFormat>TFAE#{0000000}</displayFormat>
        <label>TFAE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tests For Apex Element</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ApexElements_Util.cls
public class ApexElements_Util {
    public static void beforeMethods(map<Id, ApexElements__c> triggerOldMap, list<ApexElements__c> triggerNew) {

        TestForApexElement_Util.getInfoForRebuildTest(triggerOldMap, triggerNew, 'ApexElements__c');


        // set<Id> changedElements = new set<Id>();
        // set<Id> projectIdSet = new set<Id>();
        // for(ApexElements__c i : triggerNew){
        //     boolean updateNames = triggerOldMap == null || (triggerOldMap != null && i.Name != triggerOldMap.get(i.Id).Name);
        //     if(updateNames){
        //         i.ApexElement__c = i.Name;
        //         if(i.Id != null){
        //             changedElements.add(i.Id);
        //             projectIdSet.add(i.Project__c);
        //         }
        //     }            
        // }
        // if(!changedElements.isEmpty()){
        //     list<TestForApexElement__c> usedElements = [SELECT Id, ApexElement__c FROM TestForApexElement__c WHERE ApexElement__c IN: changedElements AND Project__c IN: projectIdSet];
        //     TestForApexElement_Util.buildRuntTestOnModify(usedElements);
        // }
        
    }

    public static void afterMethods(map<Id, ApexElements__c> triggerOldMap, list<ApexElements__c> triggerNew){
        TestForApexElement_Util.rebuildTestOnChange();
    }
}