objects/ApexElements__c.object
<CustomObject>
    <fields>
        <fullName>ApexElement__c</fullName>
        <externalId>true</externalId>
        <label>Apex Element</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Apex Elements</relationshipLabel>
        <relationshipName>Apex_Elements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Apex Element</label>
    <nameField>
        <label>Apex Element</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deployment__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Deployed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Projects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Deployment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Priority</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Deploy</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Utility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TaskItem__c.object
<CustomObject>
    <fields>
        <fullName>TaskItem__c</fullName>
        <inlineHelpText>Campos,Workflows: NombreAPIdelObjeto.NombreDelCampo
Layouts: NombreAPIdelObjeto-Nombre Del Layout
EmailTemp,Dashb.,Documents, Reports unfiled$public/NombreDeLaTemp (o) carpeta/NombreDeLaTemp</inlineHelpText>
        <label>Task Item</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Task Items</relationshipLabel>
        <relationshipName>Task_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Task Item</label>
    <nameField>
        <displayFormat>TI{00000000}</displayFormat>
        <label>Task Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TestClass__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Test Classes</relationshipLabel>
        <relationshipName>Test_Classes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TestClass__c</fullName>
        <label>Test Class</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Test Class</label>
    <nameField>
        <label>Test Class</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TestForApexElement__c.object
<CustomObject>
    <fields>
        <fullName>ApexElement__c</fullName>
        <label>Apex Element</label>
        <referenceTo>ApexElements__c</referenceTo>
        <relationshipLabel>Tests For Apex Element</relationshipLabel>
        <relationshipName>Tests_For_Apex_Element</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tests For Apex Element</relationshipLabel>
        <relationshipName>Tests_For_Apex_Element</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TestClass__c</fullName>
        <label>Test Class</label>
        <referenceTo>TestClass__c</referenceTo>
        <relationshipLabel>Tests For Apex Element</relationshipLabel>
        <relationshipName>Tests_For_Apex_Element</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test For Apex Element</label>
    <nameField>
        <displayFormat>TFAE#{0000000}</displayFormat>
        <label>TFAE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tests For Apex Element</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestForApexElement_Util.cls
public class TestForApexElement_Util {

    private static list<TestForApexElement__c> usedElements;

    
    public static void buildRuntTestOnModify(list<TestForApexElement__c> TriggerNew) {

        set<Id> apexElements = new set<Id>();
        for(TestForApexElement__c i : TriggerNew){
            apexElements.add(i.ApexElement__c);
        }

        list<ApexElements__c> aeList = [SELECT Id, Name, Project__c FROM ApexElements__c WHERE Id IN: apexElements];
        System.debug('TestForApexElement_Util - buildRuntTestOnModify - aeList - '+aeList);

        set<String> apexElementNameSet = new set<String>();
        for(ApexElements__c i : aeList){
            apexElementNameSet.add(i.Name);
        }
        map<Id, TaskItem__c> tiMap= new map<Id, TaskItem__c>([SELECT Id, Task__c, Task__r.Deployment__c FROM TaskItem__c WHERE TaskItem__c IN: apexElementNameSet AND Task__r.Status__c != 'Completed']);
        System.debug('TestForApexElement_Util - buildRuntTestOnModify - tiMap - 1 - '+tiMap);

        set<Id> theTasks = new set<Id>();
        for(TaskItem__c i : tiMap.values()){
            theTasks.add(i.Task__c);
            theTasks.add(i.Task__r.Deployment__c);
        }
        tiMap= new map<Id, TaskItem__c>([SELECT Id, Task__c FROM TaskItem__c WHERE Task__c IN: theTasks OR Task__r.Deployment__c IN: theTasks]);
        System.debug('TestForApexElement_Util - buildRuntTestOnModify - tiMap - 2 - '+tiMap);

        PackageBuilder.getInfoForBuildPackage(tiMap);

    }

    public static void beforeMethod(list<TestForApexElement__c> TriggerNew){
        set<Id> apexElements = new set<Id>();
        for(TestForApexElement__c i : TriggerNew){
            apexElements.add(i.ApexElement__c);
        }

        map<Id, ApexElements__c> aeMap = new map<Id, ApexElements__c>([SELECT Id, Name, Project__c FROM ApexElements__c WHERE Id IN: apexElements]);
        for(TestForApexElement__c i : TriggerNew){
            i.Project__c = aeMap.get(i.ApexElement__c).Project__c;
        }

    }

    public static void getInfoForRebuildTest(map<Id, SObject> triggerOldMap, list<SObject> triggerNew, String objectType){

        usedElements = new list<TestForApexElement__c>();

        map<String, map<String, String>> nameMap = new map<String, map<String,String>>{
            'TestClass__c'   => new map<String, String>{
                'Name' => 'TestClass__c',
                'Lookup' => 'TestClass__c'
            },
            'ApexElements__c' => new map<String, String>{
                'Name' => 'ApexElement__c',
                'Lookup' =>'ApexElement__c' 
            }
        };
        String nameField = nameMap.containsKey(objectType) ? nameMap.get(objectType).get('Name') : null;
        String lookupField = nameMap.containsKey(objectType) ? nameMap.get(objectType).get('Lookup') : null;

        set<String> changedElements = new set<String>();
        set<String> projectIdSet = new set<String>();
        for(SObject i : triggerNew){
            Id iId = (Id)i.get('Id');
            boolean updateNames = triggerOldMap == null || (triggerOldMap != null && (String)i.get('Name') != (String)triggerOldMap.get(iId).get('Name'));
            if(updateNames){
                if(nameField != null){
                    i.put(nameField, (String)i.get('Name')+'@'+(Id)i.get('Project__c'));
                }
                if(iId != null){
                    changedElements.add(iId);
                    projectIdSet.add((Id)i.get('Project__c'));
                }
            }            
        }

        System.debug('Util - rebuildTestOnChange - changedElements - '+changedElements);
        System.debug('Util - rebuildTestOnChange - lookupField - '+lookupField);

        if(!changedElements.isEmpty() && lookupField != null){
            String queryToGetModifiedData = 'SELECT Id, ApexElement__c FROM TestForApexElement__c WHERE Project__c IN ('+Util.convertSetToIn(projectIdSet)+') AND '+lookupField+' IN ('+Util.convertSetToIn(changedElements)+')';
            usedElements = Database.Query(queryToGetModifiedData);
            System.debug('Util - rebuildTestOnChange - usedElements - '+usedElements);
        }
    }

    public static void rebuildTestOnChange(){
        if(usedElements != null && !usedElements.isEmpty()){
            System.debug('Util - rebuildTestOnChange - usedElements - '+usedElements);
            TestForApexElement_Util.buildRuntTestOnModify(usedElements);
        }
    }
}