objects/ApexElements__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Apex Elements</relationshipLabel>
        <relationshipName>Apex_Elements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Apex Element</label>
    <nameField>
        <label>Apex Element</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deployment__c.object
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Projects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Deployment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TaskItemType__c.object
<CustomObject>
    <fields>
        <fullName>TaskItemType__c</fullName>
        <externalId>true</externalId>
        <label>Task Item Type</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Task Item Type</label>
    <nameField>
        <label>Task Item Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Item Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TestClass__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Test Classes</relationshipLabel>
        <relationshipName>Test_Classes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TestClass__c</fullName>
        <label>Test Class</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Test Class</label>
    <nameField>
        <label>Test Class</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestUtility.cls
public class TestUtility {
    public static Project__c createProject(String projectName) {
        return new Project__c(
            Name = projectName
        );
    }

    public static Task__c createTask(String taskName, Id projectId){
        return new Task__c(
            Name = taskName,
            Project__c = projectId
        );
    }

    public static TaskItemType__c createTaskItemType(String taskItemName){
        return new TaskItemType__c(
            Name = taskItemName
        );
    }

    public static Deployment__c createDeployment(String deploymentName){
        return new Deployment__c(
            Name = deploymentName
        );
    }

    public static ApexElements__c createApexElement(String apexElement, Id projectId){
        return new ApexElements__c(
            Name = apexElement,
            Project__c = projectId
        );
    }

    public static TestClass__c createTestClass(String testClass, Id projectId){
        return new TestClass__c(
            Name = testClass,
            Project__c = projectId
        );
    }
}