objects/Deployment__c.object
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ManualTask__c.object
<CustomObject>
    <fields>
        <fullName>Deployment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Manual Tasks</relationshipLabel>
        <relationshipName>Manual_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Manual Tasks</relationshipLabel>
        <relationshipName>ManualTasks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Manual Task</label>
    <nameField>
        <displayFormat>MT{00000000}</displayFormat>
        <label>Manual Task</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Deployment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaskName__c</fullName>
        <externalId>true</externalId>
        <label>Task Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TaskItem__c.object
<CustomObject>
    <fields>
        <fullName>TaskItem__c</fullName>
        <inlineHelpText>Campos,Workflows: NombreAPIdelObjeto.NombreDelCampo
Layouts: NombreAPIdelObjeto-Nombre Del Layout
EmailTemp,Dashb.,Documents, Reports unfiled$public/NombreDeLaTemp (o) carpeta/NombreDeLaTemp</inlineHelpText>
        <label>Task Item</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Task Items</relationshipLabel>
        <relationshipName>Task_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Task Item</label>
    <nameField>
        <displayFormat>TI{00000000}</displayFormat>
        <label>Task Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TaskUtility.cls
public with sharing class TaskUtility {

    public static void beforeMethods(list<Task__c> triggerNew, map<Id, Task__c> triggerOldMap){
        for(Task__c i : triggerNew){
            boolean updateNames = triggerOldMap == null || (triggerOldMap != null && i.Name != triggerOldMap.get(i.Id).Name);
            if(updateNames){
                i.TaskName__c = i.Name;
            }            
        }
    }



    public static void buldPackageOnTaskChange(list<Task__c> triggerNew, map<Id, Task__c> triggerNewMap) {

        set<Id> taskToRebuildPackage = new set<Id>();
        map<Id, Id> taskToRelateManualTask = new map<Id, Id>();

        for(Task__c i : triggerNew){
            if(triggerNewMap == null){
                if(i.Deployment__c != null){
                    taskToRebuildPackage.add(i.Deployment__c);
                }
            }else{
                if(triggerNewMap.get(i.Id).Deployment__c != i.Deployment__c){

                    if(i.Deployment__c != null){
                        taskToRebuildPackage.add(i.Deployment__c);
                    }else{
                        taskToRebuildPackage.add(triggerNewMap.get(i.Id).Deployment__c);
                    }
                    taskToRelateManualTask.put(i.Id, i.Deployment__c);
                }
            }            
        }
        System.debug('Task and deployment' + taskToRelateManualTask);

        if(!taskToRebuildPackage.isEmpty()){
            map<Id, TaskItem__c> taskItemMap = new map<Id, TaskItem__c>([SELECT Id FROM TaskItem__c WHERE Task__r.Deployment__c IN: taskToRebuildPackage]);
            PackageBuilder.getInfoForBuildPackage(taskItemMap);

        }

        if(!taskToRelateManualTask.isEmpty()){
            relateManualTasks(taskToRelateManualTask);
        }

    }

    private static void relateManualTasks(map<Id, Id> taskIdAndDeploymentId){
        list<ManualTask__c> relatedManualTasks = [SELECT Id, Task__c, Deployment__c FROM ManualTask__c WHERE Task__c IN: taskIdAndDeploymentId.keySet()];
        System.debug('relatedManualTasks' + relatedManualTasks);

        for(ManualTask__c i : relatedManualTasks){
            if(taskIdAndDeploymentId.containsKey(i.Task__c)){
                i.Deployment__c = taskIdAndDeploymentId.get(i.Task__c);
            }
        }
        System.debug('relatedManualTasks' + relatedManualTasks);

        if(!relatedManualTasks.isEmpty()){
            update relatedManualTasks;
        }
    }
}