objects/Deployment__c.object
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ManualTask__c.object
<CustomObject>
    <fields>
        <fullName>Deployment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Manual Tasks</relationshipLabel>
        <relationshipName>Manual_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Manual Tasks</relationshipLabel>
        <relationshipName>ManualTasks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Manual Task</label>
    <nameField>
        <displayFormat>MT{00000000}</displayFormat>
        <label>Manual Task</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Deployment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ManualTask_Util.cls
public class ManualTask_Util {
    public static void beforeMethods(list<ManualTask__c> triggerNew) {

        set<Id> taskId = new set<Id>();
        for(ManualTask__c i : triggerNew){
            taskId.add(i.Task__c);
        }

        map<Id, Task__c> taskMap =new map<Id, Task__c>([SELECT Id, Deployment__c FROM Task__c WHERE Id IN: taskId]);
        for(ManualTask__c i : triggerNew){
            if(taskMap.containsKey(i.Task__c)){
                i.Deployment__c = taskMap.get(i.Task__c).Deployment__c;
            }
        }
    }
}