objects/Task__c.object
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TaskItem__c.object
<CustomObject>
    <fields>
        <fullName>TaskItem__c</fullName>
        <inlineHelpText>Campos,Workflows: NombreAPIdelObjeto.NombreDelCampo
Layouts: NombreAPIdelObjeto-Nombre Del Layout
EmailTemp,Dashb.,Documents, Reports unfiled$public/NombreDeLaTemp (o) carpeta/NombreDeLaTemp</inlineHelpText>
        <label>Task Item</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Task Items</relationshipLabel>
        <relationshipName>Task_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Task Item</label>
    <nameField>
        <displayFormat>TI{00000000}</displayFormat>
        <label>Task Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TaskItemUtil.cls
public class TaskItemUtil {
    public static void rebuildPackage(map<Id, TaskItem__c> triggerNewMap) {
        set<Id> parents = new set<Id>();
        for(TaskItem__c i : triggerNewMap.values()){
            parents.add(i.Task__c);
        }
        map<Id, TaskItem__c> taskItemMap = new map<Id, TaskItem__c>([SELECT Id FROM TaskItem__c WHERE Task__c IN: parents]);

        PackageBuilder.getInfoForBuildPackage(taskItemMap);
    }
}