objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Priority</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Deploy</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Utility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TaskItem__c.object
<CustomObject>
    <fields>
        <fullName>TaskItemType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Task Item Type</label>
        <referenceTo>TaskItemType__c</referenceTo>
        <relationshipLabel>Task Items</relationshipLabel>
        <relationshipName>Task_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaskItem__c</fullName>
        <inlineHelpText>Campos,Workflows: NombreAPIdelObjeto.NombreDelCampo
Layouts: NombreAPIdelObjeto-Nombre Del Layout
EmailTemp,Dashb.,Documents, Reports unfiled$public/NombreDeLaTemp (o) carpeta/NombreDeLaTemp</inlineHelpText>
        <label>Task Item</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Task Items</relationshipLabel>
        <relationshipName>Task_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Task Item</label>
    <nameField>
        <displayFormat>TI{00000000}</displayFormat>
        <label>Task Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TaskItemType__c.object
<CustomObject>
    <fields>
        <fullName>TaskItemType__c</fullName>
        <externalId>true</externalId>
        <label>Task Item Type</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Task Item Type</label>
    <nameField>
        <label>Task Item Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Item Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TaskItemTypeUtility.cls
public class TaskItemTypeUtility {

    private static map<Id, TaskItem__c> taskItemMap;
    public static void beforeMethods(map<Id, TaskItemType__c> triggerOldMap, list<TaskItemType__c> triggerNew) {

        taskItemMap = new map<Id, TaskItem__c>();

        set<Id> changedTaskItemTypes = new set<Id>();

        for(TaskItemType__c i : triggerNew){
            boolean updateNames = triggerOldMap == null || (triggerOldMap != null && i.Name != triggerOldMap.get(i.Id).Name);
            if(updateNames){
                i.TaskItemType__c = i.Name;
                if(i.Id != null){
                    changedTaskItemTypes.add(i.Id);
                }
            }            
        }
        System.debug('TaskItemTypeUtility - beforeMethods - changedTaskItemTypes - '+changedTaskItemTypes);

        if(!changedTaskItemTypes.isEmpty()){
            taskItemMap = new map<Id, TaskItem__c>([SELECT Id FROM TaskItem__c WHERE TaskItemType__c IN: changedTaskItemTypes AND Task__r.Status__c NOT IN: new set<String>{'Completed', 'Utility'}]);
            System.debug('TaskItemTypeUtility - beforeMethods - taskItemMap - '+taskItemMap);
        }
       
    }

    public static void afterMethods(map<Id, TaskItemType__c> triggerOldMap, list<TaskItemType__c> triggerNew){

        if(taskItemMap != null && !taskItemMap.isEmpty()){
            System.debug('TaskItemTypeUtility - beforeMethods - taskItemMap - '+taskItemMap);

            PackageBuilder.getInfoForBuildPackage(taskItemMap);
        }
    }
}